name: chess_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  stockfish: ^1.7.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "pieces/W_king.png"
  min_sdk_android: 21
flutter:
  uses-material-design: true
  assets:
    - pieces/
    